### ISSUE TITLE
Filter einführen, der Hörfassungen und Kurzfeatures vom Download ausschliesst

### ISSUE THREAD

**Issue by nitschkecm** [dicer/auto-tatort#1]
Hi, 

ich freue mich sehr über Dein Script und habe es auf einem Raspberry PI zum laufen gebracht. Allerdings bekomme ich teilweise nicht den Tatort selber heruntergeladen sonder nur die Hörfassung. Gibt es eine Möglichkeit es besser zu Filtern?
Hier die File List die ich habe... 
![screen shot 2014-08-11 at 12 50 00](https://cloud.githubusercontent.com/assets/8415024/3874701/42b01524-2145-11e4-8989-3de85f91dbaf.png)
Jeder Hinweiss / Tip ist mehr als nur Willkommen! 

Vielen Dank !
Carsten

**Comment by nitschkecm** [comment]
Hallo, 
ich geniesse Weiterhin das script und somit Tatort! Hast Du eine Möglichkeit gefunden mit der man dei Hörfassung ausschliessen kann ?

**Comment by dicer** [comment]
Man muesste eigentlich nur die Feeditems durchgehen und entsprechend filtern. Da ja aber durchaus Leute die Hoerfassung haben wollen (und vielleicht NUR dir), brauche ich dafuer eigentlich endlich mal ne richtige Config. Aus dem Grund ist da bisher nichts passiert. Irgendwann... ;)

**Comment by x42** [comment]
quick hack: https://github.com/x42/auto-tatort/commit/4e8d0db20ab333c634e0d5f3a156ac0d1751c11d

**Comment by dicer** [comment]
Mit Version 2.0.00 erledigt
