### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by olreti** [dicer/auto-tatort#10]
Schönes Skript. Teste grad n bisschen die v2.

Bekomme mit dem Mitternachtsspitzen-Feed das hier beim fünften Eintrag:

````python
Traceback (most recent call last):
  File "/home/pi/bin/autotatort/auto-tatort/autoTatort.py", line 165, in <module>
    mediaLinks = media["_mediaArray"][1]["_mediaStreamArray"]
IndexError: list index out of range

**Comment by dicer** [comment]
Hab mir das gerade mal angesehen: Bei dem Item ist leider kein mp4 hinterlegt, sondern ein adaptiver Stream. Dafuer gibt es im Moment keinen Support (einfach weil der Tatort das nicht benutzt). Ich werde aber noch eine entsprechende Fehlermeldung einbauen und den Fehler fangen, damit das Script weiter probieren kann.

**Comment by dicer** [comment]
Machbar waere das aber durchaus wenn ich das richtig sehe. Man muss nur ein paar mehr Files runterladen und dann die einzelnen mp4 Teile irgendwie zusammen setzen.
Wenn du das umsetzen moechtest, kann ich mir durchaus vorstellen das in das Script zu uebernehmen. Am besten mit zwei Methoden: Eine bekommt das media["_mediaArray"] uebergeben und gibt einen String zurueck. Sowas wie DirectDownload oder AdaptiveStream.
Danach entscheidet das Hauptprogramm ob es weitermacht wie bisher oder das ganze deiner zweiten Methode ueberlaesst. Damit bleibt der Tatortcode so wie er ist und ist leichter pflegbar.

**Comment by olreti** [comment]
Das Abfangen funktioniert, vielen Dank für den Trotzdem-Fix :)
Die Idee klingt gut. Werde mir mal anschauen, ob das sich irgendwie mit meinem noch etwas limitierten Programmierhorizont in Einklang bringen lässt. Wenn wieder etwas Zeit ist, seufz...
