### ISSUE TITLE
Aktuell funktioniert auto-tatort nicht - änderung der API?

### ISSUE THREAD

**Issue by langhaarschneider** [dicer/auto-tatort#11]
Hallo,

hat die ARDMediathek vielleicht irgendwas verändert? Bei den letzten beiden Aufrufen von auto-tatort via cronjob bekam ich folgende Fehlermeldung:

> Traceback (most recent call last):
>   File "/home/pi/bin/autoTatort.py", line 101, in <module>
>     urlretrieve(mediaURL, TARGET_DIR + fileName + ".mp4")
>   File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
>     return opener.retrieve(url, filename, reporthook, data)
>   File "/usr/lib/python2.7/urllib.py", line 289, in retrieve
>     "of %i bytes" % (read, size), result)
> urllib.ContentTooShortError: retrieval incomplete: got only 300621911 out of 1310005972 bytes

Kann das jemand bestätigen, hat jemand eine Lösung?

**Comment by dicer** [comment]
Also mit der API ist alles ok. Bei mir gingen auch der am Freitag und der gestern ohne Probleme.
Sieht so aus, als wuerde der Download mitten drin abbrechen (nach knapp 300MB). Ich tippe daher eher auf schlechte Netzanbindung? Hatte den Fehler naemlich noch nie.
Ich schau mir mal bei Gelegenheit an, ob ich das irgendwie abfangen kann und den Download wieder aufnehmen kann. Ich befuerchte aber das ist mehr Arbeit als ich umsetzen moechte ;)

Hab uebrigens gerade Version 2 released. Mit der kannst du immerhin das File loeschen und er versucht es nochmal.

**Comment by langhaarschneider** [comment]
Hab jetzt Version 2 im Einsatz - die funktioniert. Vielen Dank!
