### ISSUE TITLE
Trying to Download "Lindenstraße"

### ISSUE THREAD

**Issue by heikone** [dicer/auto-tatort#17]
Dear dicer,
I've found your wonderful py script, that helps a lot to download Tatort.
But additionally, I would like to download Lindenstraße with the help of the following config.json:

{
    "debug": 1,
    "debugFile": "debug.log",
    "feeds": [
        {
            "enabled": 1,
            "id": "Lindenstrasse",
            "quality": -1,
            "subtitles": 0,
            "targetFolder": "/mnt/seagate/gemeinsam/Filme_Serien/Lindenstrasse/",
            "url": "https://www.ardmediathek.de/tv/Lindenstra%C3%9Fe/Sendung?documentId=5280&bcastId=5280&rss=true",
            "exclude": [
                {
                    "regexp": ".*Vorschau.*"
                },
                {
                    "regexp": ".*Outtake.*"
                },
                {
                    "regexp": ".*So geht.*"
                }
            ],
            "titleFilters": [
                {
                    "replace": " (Video tgl. ab 22 Uhr)"
                },
                {
                    "replace": " (Video tgl. ab 20 Uhr)"
                }
            ],
            "titlePrependItemDate": 0
        }
    ],
    "downloadedFeedItemsDatabase": "downloadedItems.json",
    "version": 5
}

But I'm not successful.
The script sucessfully finds a file to download, but it does not start and after a while it tells me, that the file with the requested quality could not be downloaded.
Downloading the given file manually works fine ...

Maybe you can help.

Best regards
Heiko

**Comment by heikone** [comment]
The exact message during the fail is:

> Could not connect to link '//wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/171/1712003/1712003_19909247.mp4'
> [Errno ftp error] [Errno 110] Connection timed out
> Could not download 'Lindenstraße - Folge 1683 "Geschäftsmänner"' because of an error or nothing matching your quality selection

Greetings
Heiko

**Comment by heikone** [comment]
Was easy to solve:
Just add `mediaURL = "https:" + mediaURL` in the py script before the download starts (i.e. in line 241).

**Comment by dicer** [comment]
Yes, this does help for some feeds. It will break others though, because some feeds do contain correct media urls, some don't.
I'm reopening this issue so I remember to check for this and fix it properly
