### ISSUE TITLE
Is it broken now?

### ISSUE THREAD

**Issue by Ramblurr** [dicer/auto-tatort#18]
It seems something has changed. 

The tool is only downloading the "Lammerts Leichen" clips and not the full episodes.

**Comment by dicer** [comment]
Works for me and downloads a current Tatort. Could you post your config and some more details about the environment please (platform, python version).

**Comment by Ramblurr** [comment]
Hmm.. I've checked back now and it seems to be working again, it missed several episodes from March - April, and instead downloaded these other smaller clips. But the past three downloaded with out issue.

I'll close this unless I can repro it again, thanks!
