### ISSUE TITLE
Untertitel runter laden und konvertieren

### ISSUE THREAD

**Issue by dicer** [dicer/auto-tatort#6]
Viele (alle?) Tatort-Folgen enthalten Untertitel in einer XML Datei:
"_subtitleUrl":"/static/avportal/untertitel_mediathek_preview/23229170.xml","_subtitleOffset":0,"

-> http://www.ardmediathek.de/static/avportal/untertitel_mediathek_preview/23229170.xml

Die Zeit beginnt zwar bei 10:00:00.000 aber ansonsten sollte man das recht problemlos in ein Format konvertieren koennen, welches normale Player abspielen koennen. SRT zb

Erster Schritt: Schon mal die Untertitel runter laden
Zweiter Schritt: Konvertieren

**Comment by haraldF** [comment]
https://github.com/haraldF/ttaf2srt ist ein Konverter nach SRT

**Comment by dicer** [comment]
Oh cool! Habe zwar immer noch einen Pullrequest offen, der auch genau das angeht, aber irgendwie gefaellt mir ein externes Tool doch besser. Unix und so.
Hast du den mal angeschaut und kannst mir sagen ob der besser oder schlechter ist?

**Comment by dicer** [comment]
Ich habe mal den Konverter von @haraldF eingebunden. Wenn es jemand testen moechte: https://github.com/dicer/auto-tatort/tree/srt
Wenn das die naechsten Wochen stabil laeuft, dann wirds in master gemerged

**Comment by dicer** [comment]
Mit commit abf1b705aa312ad3d1db2a700b21660275930d7f erledigt
