### ISSUE TITLE
Startschwierigkeiten

### ISSUE THREAD

**Issue by Ph1r3ph0x** [dicer/auto-tatort#8]
Erstmal besten Dank für dieses tolle Skript! Leider bekomme ich es bei mir nicht zum laufen :( Habe es auf die Fritzbox gepackt (mit freetz) und bekomme folgende Fehlerausgabe:
```python
Traceback (most recent call last):
  File "autotatort.py", line 73, in <module>
    urlretrieve(mediaURL, TARGET_DIR + fileName + ".mp4")
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
  File "/usr/lib/python2.7/urllib.py", line 249, in retrieve
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 53: ordinal not in range(128)
```

Auf meinem richtigen PC erhalte ich folgende Fehlermeldung:
```python
    print "Could not get item with title '" + title + "'. Got redirected to '" + response.geturl() + "'. This is probably because the item is still in the RSS feed, but not available anymore."
                                          ^
SyntaxError: invalid syntax
```
Irgendwelche Ideen?

Liebe Grüße

**Comment by dicer** [comment]
Das sieht alles nach UTF8 Problemen aus. Gut, dass du gerade testest, da natuerlich genau der gestrige Tatort Sonderzeichen enthaelt :) Ansonsten haette es erstmal geklappt. Wobei es mir unter Debian auch weiterhin funktioniert. Aber unter python ist UTF8 eh mein liebstes Thema...
Versuch doch bitte mal den branch "issue8". Habe ein paar Fixes eingebaut, die weiterhelfen koennten.

**Comment by dicer** [comment]
Achja: Da das Script ja immer nur auf den heutigen Tag sucht, findet es natuerlich den Tatort von gestern nicht. Also am besten die Zeile
today = datetime.date.today()
austauschen gegen:
today = datetime.date(2015,5,31)

**Comment by dicer** [comment]
@Ph1r3ph0x Konntest du nochmal testen?

**Comment by Ph1r3ph0x** [comment]
Huhu, ich weiß gar nicht, ob ich hier zurückschreiben kann..
Ich habe mittlerweile mal getestet und "Issue8" scheint zu funktionieren.
Beim Master Branch ging es immernoch nicht, ich hab die Problematik aber
folgendermaßen gelöst:
      fileName = fileName.replace(u'ä', 'ae')
      fileName = fileName.replace(u'ö', 'oe')
      fileName = fileName.replace(u'ü', 'ue')

Geht bestimmt eleganter, aber python ist einfach nicht so meins. Jetzt
funktioniert alles ;) Danke, dass du dir so eine Arbeit machst und das
alles so toll weiterentwickelst! ;)
Lg Ph1r3ph0x

2016-02-04 13:25 GMT+01:00 Felix Knecht <notifications@github.com>:

**Comment by dicer** [comment]
Gerade UTF8 ist in Python auch nicht wirklich meins... Dein Patch
duerfte ne Weile funktionieren bis dann noch ein anderes Sonderzeichen
kommt. Zb ß ;)
Wenn issue8 bei dir funktioniert, muss ich das wohl mal auf den
aktuellen master portieren. Koennte aber noch ne Weile dauern, da ich im
Moment keine Zeit fuer nix hab. Ich lass die Issue aber mal auf zur
Erinnerung!
