### ISSUE TITLE
Keine Downloads mehr

### ISSUE THREAD

**Issue by nitschkecm** [dicer/auto-tatort#9]
Hallo, 

ich habe das script auf meinem Raspbian (raspberry pi) jeden tag um 23:00 Uhr laufen. Aber in den letzen Wochen wird kein Tatort mehr heruntergeladen. Hat sich was bei ardmediathek verändert ?
Bin ich der einzige oder geht es allen so ?

**Comment by dicer** [comment]
Mist, dachte es waere Sommerpause... Stellt sich raus, dass die ARD keine hohe Qualitaet mehr anbietet... Nur noch 640x360 statt 960x544 vorher...
Siehe auch http://forum.digitalfernsehen.de/forum/ard-zdf-rtl-sat-1-co-alles-im-und-ueber-das-free-tv/348696-ard-verschlechtert-bitrate-der-mediathek.html

Hab nen Fix eingebaut, der automatisch die hoechste Quali zieht.

**Comment by nitschkecm** [comment]
Hi, 

habe gerade Deinen Fix eingespielt und leider … tut sich nix. Wenn ich das Program mit python autoTatort.py starte dann dauert es ca 3 sekunden und dann ist das Programm zu ende. Kann es sein das es da noch einen Fehler gibt ? Denn ich kann den Tatort online sehen. 

Vielen Dank nochmal 

Carsten

**Comment by nitschkecm** [comment]
Ich habe nochmal die vorherige version genommen und dann
today = datetime.date(2015,8,30) eingestellt so das es auf den thread von gestern geht. 
dabei kam dann diese Fehlermeldung. 

Traceback (most recent call last):
  File "autoTatort.old", line 72, in <module>
    urlretrieve(mediaURL, TARGET_DIR + fileName + ".mp4")
  File "/usr/lib/python2.7/urllib.py", line 93, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 227, in retrieve
    url = unwrap(toBytes(url))
  File "/usr/lib/python2.7/urllib.py", line 1056, in unwrap
    url = url.strip()
AttributeError: 'list' object has no attribute 'strip'

**Comment by dicer** [comment]
Stimmt, das ist die zweite Aenderung: Es kommen auf einmal zwei URLs zu mp4 Dateien zurueck. Magst du mal schauen welcher die Richtige ist? Bin momentan nicht so gut ans Netz angebunden.
Einfach die documentId aus der URL der Webseite nehmen und hier einsetzen: http://www.ardmediathek.de/play/media/XXXXXXX?devicetype=pc&features=flash
Da sind es dann die beiden letzten URLs (beide bei "_quality":2)

**Comment by nitschkecm** [comment]
Hi

ich habe diese hier 


http://www.ardmediathek.de/tv/Tatort/Er-wird-töten-Video-tgl-ab-20-Uhr/Das-Erste/Video?documentId=30321394&bcastId=602916 <http://www.ardmediathek.de/tv/Tatort/Er-wird-t%C3%B6ten-Video-tgl-ab-20-Uhr/Das-Erste/Video?documentId=30321394&bcastId=602916>

ich habe leider die URL wie Du sie beschrieben hast nicht finden können. 

Carsten

**Comment by dicer** [comment]
Habs mir gestern nochmal genauer angesehen und die Mediathek hat nun mehr Qualitaetsstufen und ein geaendertes Rueckgabeformat diesbezueglich. Der letzte Checkin sollte das nun soweit beheben, dass immerhin ein paar Qualitaetsstufen waehlbar sind (natuerlich auch die hoechste) und nun auch eine Warnung kommt, wenn er die geforderte Qualitaet nicht finden kann. Mit -1 sollte er aber immer was downloadbares finden.

**Comment by dicer** [comment]
Irgendwie wurden am Freitag und Sonntag die Folgen nicht im RSS-Feed
gefunden. Jedenfalls bei mir. Stattdessen hat er unter der Woche aber
auf einmal einen weiteren Tatort runtergeladen. Allerdings den gleichen
an zwei verschiedenen Tagen und heute ist er nicht mehr im RSS.
Alles sehr komisch im Moment.

Ich befuerchte allerdings, dass ich doch langsam mal die Unabhaengigkeit
zum aktuellen Datum einbauen muss und mir irgendwie die schon
gesehenen/runtergeladenen Folgen merken muss. Scheint so, als wuerden
mittlerweile die Folgen erst am naechsten Tag im RSS-Feed auftauchen und
er sie deswegen nicht finden.

Die Probleme mit der Qualitaet in dieser Issue sollten allerdings
trotzdem erledigt sein.

**Comment by nitschkecm** [comment]
Hallo, 

habe es am Freitag mit dem Datum 2015,8,30 laufen lassen und funktionierte bestens. Gestern normal mit cron getriggert und ebenfalls bestens. 

Wenn man nur die Hörfassung weglassen könnte ;) wäre es 100% perfect !

**Comment by dicer** [comment]
Hab auch gesehen woran es bei mir lag: Hatte noch ausversehen ein festes
Datum mit drin... Damit kann ich die Issue dann hier wirklich
geschlossen lassen.
Hoerfassung steht schon recht weit oben auf der Liste. Das wird das
naechste sein. Und sei es nur ein spezieller Parameter dafuer, anstatt
was generellem.
